package me.cyljacky02.loafylib.glow

import net.kyori.adventure.text.format.NamedTextColor
import org.bukkit.Color
import org.bukkit.Location
import org.bukkit.util.Transformation
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * Per-player state container for glowing entities and displays.
 *
 * All collections are thread-safe for concurrent access from multiple threads
 * (main thread, async tasks, Netty threads).
 */
internal class PlayerGlowData {
    /**
     * Entity ID -> GlowState for existing entities that are glowing for this player.
     */
    val glowingEntities: ConcurrentHashMap<Int, GlowState> = ConcurrentHashMap()

    /**
     * Virtual entity ID -> DisplayState for display entities visible to this player.
     */
    val activeDisplays: ConcurrentHashMap<Int, DisplayState> = ConcurrentHashMap()

    /**
     * Team colors already sent to this player (avoid duplicate team creation packets).
     */
    val sentTeamColors: ConcurrentHashMap.KeySetView<NamedTextColor, Boolean> =
        ConcurrentHashMap.newKeySet()

    /**
     * Virtual entity ID -> MarkerState for shulker markers visible to this player.
     */
    val activeMarkers: ConcurrentHashMap<Int, MarkerState> = ConcurrentHashMap()
}

/**
 * State for an existing entity that is glowing for a specific player.
 *
 * @property entityId the Minecraft entity ID
 * @property color the glow color (team color)
 */
internal data class GlowState(
    val entityId: Int,
    val color: NamedTextColor
)

/**
 * State for a virtual display entity visible to a specific player.
 *
 * @property entityId the virtual entity ID (negative, generated by service)
 * @property type the type of display entity
 * @property location the spawn location
 * @property color the RGB glow color
 * @property transform the current transformation (null if default)
 */
internal data class DisplayState(
    val entityId: Int,
    val type: DisplayType,
    val location: Location,
    val color: Color,
    val transform: Transformation?
)

/**
 * Types of display entities that can be spawned.
 */
internal enum class DisplayType {
    BLOCK,
    ITEM,
    TEXT
}

/**
 * State for a virtual shulker marker (invisible glowing shulker) visible to a specific player.
 *
 * @property entityId the virtual entity ID (negative, generated by service)
 * @property entityUuid the entity UUID (used for team membership)
 * @property location the spawn location (block-aligned)
 * @property color the glow color (team color, 16 options)
 */
internal data class MarkerState(
    val entityId: Int,
    val entityUuid: UUID,
    val location: Location,
    val color: NamedTextColor
)
