package me.cyljacky02.loafylib;

import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
import io.papermc.paper.plugin.loader.PluginLoader;
import io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver;
import org.eclipse.aether.artifact.DefaultArtifact;
import org.eclipse.aether.graph.Dependency;
import org.eclipse.aether.repository.RemoteRepository;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Paper PluginLoader that loads dependencies via Paper's library loader.
 *
 * <p>
 * IMPORTANT: This class must be Java, not Kotlin, because it runs before the
 * library loader has loaded Kotlin stdlib.
 *
 * <p>
 * The dependency coordinates are NOT written here. They are generated from the
 * {@code paperLibrary} configuration in {@code build.gradle.kts} (which in turn
 * reads {@code gradle/libs.versions.toml}) and packaged into this jar as
 * {@value #LIBRARIES_RESOURCE}. That indirection exists because the versions we
 * compile against and the versions Paper fetches at runtime MUST match: when
 * they were maintained as two hand-edited lists, an automated dependency bump
 * could update one and not the other, producing a build that passes CI and then
 * throws {@code NoSuchMethodError} on a live server.
 *
 * <p>
 * LoafyLib provides shared dependencies for all Loafy plugins:
 * <ul>
 * <li>Kotlin stdlib, reflect, coroutines and serialization</li>
 * <li>HikariCP for database connection pooling</li>
 * <li>MariaDB and SQLite JDBC drivers</li>
 * <li>Configurate for YAML/HOCON configuration</li>
 * <li>Reactor Core for Lettuce reactive streams</li>
 * </ul>
 *
 * <p>
 * Shaded dependencies (in the jar, not loaded here):
 * <ul>
 * <li>Lettuce (Redis client) - relocated to avoid classloader conflicts</li>
 * <li>InvUI (GUI framework) - NOT relocated (uses Paper's native Netty)</li>
 * </ul>
 *
 * <p>
 * NOTE: We intentionally DO NOT load netty-resolver-dns here. Paper already has
 * Netty loaded. If we load netty-resolver-dns, Lettuce's
 * {@code DefaultClientResources} static initializer creates a
 * {@code DnsAddressResolverGroup}, which triggers {@code DnsNameResolver}'s
 * static initializer to register the AttributeKey
 * {@code io.netty.resolver.dns.pipeline}. Paper's Netty already registered that
 * key, so this throws {@code IllegalArgumentException}. Without
 * netty-resolver-dns on the classpath, Lettuce falls back to
 * {@code DefaultAddressResolverGroup.INSTANCE} (the JDK's blocking DNS
 * resolver), which is what {@code LettuceRedisManager} configures explicitly.
 */
@SuppressWarnings("UnstableApiUsage")
public class LoafyLibPluginLoader implements PluginLoader {

        /** Generated by the {@code :generatePaperLibraries} Gradle task. */
        private static final String LIBRARIES_RESOURCE = "/me/cyljacky02/loafylib/libraries.txt";

        private static final String SPONGE_REPOSITORY = "https://repo.spongepowered.org/repository/maven-public/";

        @Override
        public void classloader(@NotNull PluginClasspathBuilder classpathBuilder) {
                MavenLibraryResolver resolver = new MavenLibraryResolver();

                // Add Maven Central mirror (required by Paper ToS)
                resolver.addRepository(
                                new RemoteRepository.Builder("central", "default",
                                                MavenLibraryResolver.MAVEN_CENTRAL_DEFAULT_MIRROR)
                                                .build());

                // Add Sponge repository for Configurate
                resolver.addRepository(
                                new RemoteRepository.Builder("sponge", "default", SPONGE_REPOSITORY)
                                                .build());

                for (String coordinate : readLibraryCoordinates()) {
                        resolver.addDependency(new Dependency(new DefaultArtifact(coordinate), null));
                }

                classpathBuilder.addLibrary(resolver);
        }

        /**
         * Reads the generated dependency manifest from this plugin's jar.
         *
         * <p>
         * Fails loudly rather than degrading: a missing or empty manifest means the
         * jar was built without {@code :generatePaperLibraries}, and letting the
         * plugin start would produce a far more confusing
         * {@code NoClassDefFoundError} for Kotlin stdlib later on.
         */
        private static List<String> readLibraryCoordinates() {
                List<String> coordinates = new ArrayList<>();

                try (InputStream input = LoafyLibPluginLoader.class.getResourceAsStream(LIBRARIES_RESOURCE)) {
                        if (input == null) {
                                throw new IllegalStateException(
                                                "Missing " + LIBRARIES_RESOURCE + " in the LoafyLib jar. "
                                                                + "Build with './gradlew build' so :generatePaperLibraries runs.");
                        }

                        BufferedReader reader = new BufferedReader(
                                        new InputStreamReader(input, StandardCharsets.UTF_8));

                        String line;
                        while ((line = reader.readLine()) != null) {
                                String trimmed = line.trim();
                                if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                                        continue;
                                }
                                coordinates.add(trimmed);
                        }
                } catch (IOException exception) {
                        throw new UncheckedIOException(
                                        "Failed to read " + LIBRARIES_RESOURCE + " from the LoafyLib jar",
                                        exception);
                }

                if (coordinates.isEmpty()) {
                        throw new IllegalStateException(
                                        LIBRARIES_RESOURCE + " contained no dependency coordinates.");
                }

                return coordinates;
        }
}
